<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Tipe Pekerjaan --Ang</name>
   <tag></tag>
   <elementGuidId>425789b9-f70c-4cdd-a232-eaf0dccb8daf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_mrtw_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-field-2 ut-border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ap_mrtw_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Tipe Pekerjaan --Anggota Parlemen (DPR, MPR, DPRD)Hakim, Pejabat di Pengadilan Insinyur Pengebor Minyak Lepas PantaiKonsultan Hukum, PengacaraNotarisPegawai NegeriPegawai SwastaPejabat Militer/Polisi   Pelaut/Kapten KapalPemuka Agama / PendetaPengusahaWiraswasta</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_mrtw_id&quot;)</value>
   </webElementProperties>
</WebElementEntity>
