<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Kelurahan --Ab</name>
   <tag></tag>
   <elementGuidId>78a02322-ca87-4b6e-ad4e-92789381011d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_employer_kelurahan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-field-2 ut-border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ap_employer_kelurahan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
-- Pilih Kelurahan --Abang SonganAbuanAwanBantangBanuaBatu DindingBatukaangBatur SelatanBatur TengahBatur UtaraBayungcerikBayunggedeBelancanBelandinganBelangaBelantihBinyanBonyohBuahanBunutinCaturDaupDausaGunungbauKatungKedisanKintamaniKutuhLanggahanLembeanMangguhManikliyuMenganiPengejaranPingganSatraSekaanSekardadiSelulungSerahiSiyakinSongan ASongan BSubayaSukawanaSuterTerunyanUlian</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_employer_kelurahan&quot;)</value>
   </webElementProperties>
</WebElementEntity>
