<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya2</name>
   <tag></tag>
   <elementGuidId>d3059008-802e-41c5-a0f3-aa9d5f2de58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;step2&quot;)/div[@class=&quot;ut-form-box2 clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ut-form-content&quot;]/button[@class=&quot;btn-next&quot;][count(. | //button[@class = 'btn-next' and @onclick = concat('javascript:Applicant.submitForm(' , &quot;'&quot; , 'step2' , &quot;'&quot; , ', ' , &quot;'&quot; , 'step3' , &quot;'&quot; , ');return false;') and (text() = 'Selanjutnya' or . = 'Selanjutnya')]) = count(//button[@class = 'btn-next' and @onclick = concat('javascript:Applicant.submitForm(' , &quot;'&quot; , 'step2' , &quot;'&quot; , ', ' , &quot;'&quot; , 'step3' , &quot;'&quot; , ');return false;') and (text() = 'Selanjutnya' or . = 'Selanjutnya')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Applicant.submitForm('step2', 'step3');return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step2&quot;)/div[@class=&quot;ut-form-box2 clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ut-form-content&quot;]/button[@class=&quot;btn-next&quot;]</value>
   </webElementProperties>
</WebElementEntity>
