<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya3</name>
   <tag></tag>
   <elementGuidId>98a9a6f5-d3b2-4f41-9d3b-c7372c9c42f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;step3&quot;)/div[@class=&quot;ut-form-box2 clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ut-form-content&quot;]/button[@class=&quot;btn-next&quot;][count(. | //button[@class = 'btn-next' and @onclick = concat('javascript:Applicant.submitForm(' , &quot;'&quot; , 'step3' , &quot;'&quot; , ', ' , &quot;'&quot; , 'step4' , &quot;'&quot; , ');return false;') and (text() = 'Selanjutnya' or . = 'Selanjutnya')]) = count(//button[@class = 'btn-next' and @onclick = concat('javascript:Applicant.submitForm(' , &quot;'&quot; , 'step3' , &quot;'&quot; , ', ' , &quot;'&quot; , 'step4' , &quot;'&quot; , ');return false;') and (text() = 'Selanjutnya' or . = 'Selanjutnya')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Applicant.submitForm('step3', 'step4');return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step3&quot;)/div[@class=&quot;ut-form-box2 clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ut-form-content&quot;]/button[@class=&quot;btn-next&quot;]</value>
   </webElementProperties>
</WebElementEntity>
